---
title: "convert images"
output: html_document
date: "2023-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load libraries
```{r}
# Load required packages
library(EBImage)
library(SpatialPack)
```

Choose variables
```{r}
#Pick one technique: "denoise" "power" "thresholding" "opening"
technique = "opening"

#Path: Change it to your path but right before the cluster number. eg."../data/Biotechnology/data_processed/cell_images/cluster_"
#INPUT:
folder_path = "../data_merged_augmented/Biotechnology/data_processed/cell_images/cluster_"
#OUTPUT:
output_path = paste0("../data_",technique,"/Biotechnology/data_processed/cell_images/cluster_")

#Create output folder
if (!file.exists(paste0("../data_",technique))) {
  system(paste0("mkdir ",paste0("../data_",technique)))
  system(paste0("mkdir ",paste0("../data_",technique,"/Biotechnology/")))
  system(paste0("mkdir ",paste0("../data_",technique,"/Biotechnology/data_processed/")))
  system(paste0("mkdir ",paste0("../data_",technique,"/Biotechnology/data_processed/cell_images/")))
}

#Change if you are converting one cluster, If you are running all clusters then ignore this variable 
cluster = "1"
```

functions
```{r}
denoise_filter <- function(img){
  img = denoise(as.matrix(img), type="enhanced") 
  return(img)
}

power_filter <- function(img){
  img = img^2.5
  return(img)
}

thresholding_filter <- function(img){
  img = thresh(img, w=9, h=8, offset=0.05)
  img = fillHull(opening(img, makeBrush(5, shape='diamond')))
  return(img)
}

opening_filter <- function(img){
  img = opening(img, makeBrush(5, shape='diamond'))
  return(img)
}
```

RUN THIS For 1 cluster
```{r}
image_files <- list.files(paste0(folder_path,cluster,"/"),
                             full.names = TRUE)
cell_names <- list.files(paste0(folder_path,cluster,"/"),
                             full.names = FALSE)
#name it based on the method 
output_folder <- paste0(output_path,cluster,"/")



# if there is no folder for the cluster, create one
if (!file.exists(output_folder)) {
    system(paste0("mkdir ",output_folder))
}

i = 1
while (i <= length(image_files)) {
  # Read image
  img <- readImage(image_files[i])

  #Apply image processing technique
  if (technique == "denoise") {
    img = denoise_filter(img)
  } else if (technique == "power") {
    img = power_filter(img)
  } else if (technique == "thresholding") {
    img = thresholding_filter(img)
  } else if (technique == "opening") {
    img = opening_filter(img)
  }
  
  # Save transformed image to output file
  EBImage::writeImage(x = img, files = paste0(output_folder,cell_names[i]))
  i = i+1
}
```

RUN THIS for ALL 28 clusters - change to 17
```{r}
cluster_numer = 17
for(j in 1:cluster_numer){
  image_files <- list.files(paste0(folder_path,j,"/"),
                               full.names = TRUE)
  cell_names <- list.files(paste0(folder_path,j,"/"),
                               full.names = FALSE)
  #name it based on the method 
  output_folder <- paste0(output_path,j,"/")
  
  
  # if there is no folder for the cluster, create one
  if (!file.exists(output_folder)) {
      system(paste0("mkdir ",output_folder))
  }
  
  i = 1
  while (i <= length(image_files)) {
    # Read image
    img <- readImage(image_files[i])
    
    #Apply image processing technique
    if (technique == "denoise") {
      img = denoise_filter(img)
    } else if (technique == "power") {
      img = power_filter(img)
    } else if (technique == "thresholding") {
      img = thresholding_filter(img)
    } else if (technique == "opening") {
    img = opening_filter(img)
    }
   
    
    # Save transformed image to output file
    EBImage::writeImage(x = img, files = paste0(output_folder,cell_names[i]))
    i = i+1
  }
}


```


